apiVersion: v1
kind: ConfigMap
metadata:
  name: noti-service-config
data:
  SPRING_PROFILES_ACTIVE: "default"
  SERVER_PORT: "8084"
  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/noti_db"
  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8080"
