apiVersion: v1
kind: Secret
metadata:
  name: noti-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "noti_service"
  SPRING_DATASOURCE_PASSWORD: "changeme"
  FIREBASE_CREDENTIALS: "changeme"
