apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "user_service"
  SPRING_DATASOURCE_PASSWORD: "changeme"
  JWT_SECRET: "changeme-jwt-secret-key"
