apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

images:
  - name: wealist/storage-service
    newName: storage-service
    newTag: local

replicas:
  - name: storage-service
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: storage-service-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: "dev"
