apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

images:
  - name: noti-service
    newName: noti-service
    newTag: local

replicas:
  - name: noti-service
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: noti-service-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "dev"
