# =============================================================================
# Kustomization - Shared Resources
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-shared.yaml
  - secret-shared.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: wealist
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
