apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secret
type: Opaque
stringData:
  DB_USER: "chat_service"
  DB_PASSWORD: "chat_service_password"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-min-32-chars"
