apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-service-config
data:
  ENV: "dev"
  SERVER_PORT: "8003"
  SERVER_MODE: "debug"
  SERVER_BASE_PATH: "/api"
  LOG_LEVEL: "info"
  AUTH_API_BASE_URL: "http://auth-service:8080"
  USER_SERVICE_URL: "http://user-service:8081"
  CORS_ALLOWED_ORIGINS: "*"
