apiVersion: v1
kind: Secret
metadata:
  name: storage-service-secret
type: Opaque
stringData:
  DB_USER: "storage_service"
  DB_PASSWORD: "storage_service_password"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-min-32-chars"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
