apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-prod

resources:
  - ../../base

images:
  - name: noti-service
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/wealist/noti-service
    newTag: ${IMAGE_TAG}

replicas:
  - name: noti-service
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: noti-service-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "prod"
      - op: replace
        path: /data/SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://${RDS_ENDPOINT}:5432/noti_db"
