# PostgreSQL Kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: wealist
