apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
data:
  turnserver.conf: |
    listening-ip=0.0.0.0
    listening-port=3478
    realm=localhost
    server-name=wealist-turn
    lt-cred-mech
    user=wealist:wealist123
    no-cli
    no-dtls
    log-file=stdout
    verbose
    allow-loopback-peers
    fingerprint
    mobility
    min-port=49152
    max-port=65535
    no-multicast-peers
