apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: coturn
      app.kubernetes.io/component: turn-server
      app.kubernetes.io/part-of: wealist
