apiVersion: v1
kind: Service
metadata:
  name: coturn
  labels:
    app: coturn
spec:
  type: NodePort
  ports:
    - port: 3478
      targetPort: 3478
      nodePort: 30478
      protocol: UDP
      name: stun-udp
    - port: 3478
      targetPort: 3478
      nodePort: 30479
      protocol: TCP
      name: stun-tcp
  selector:
    app: coturn
