apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

patchesStrategicMerge:
  - configmap-patch.yaml

images:
  - name: frontend
    newName: frontend
    newTag: local

replicas:
  - name: frontend
    count: 2
