apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

images:
  - name: auth-service
    newName: auth-service
    newTag: local

replicas:
  - name: auth-service
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: auth-service-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "dev"
      - op: add
        path: /data/OAUTH2_CLIENT_REDIRECT_URI
        value: "http://localhost:8080/login/oauth2/code/google"
      - op: add
        path: /data/OAUTH2_REDIRECT_URL_ENV
        value: "http://localhost:8080/oauth/callback"
