apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

images:
  - name: user-service
    newName: user-service
    newTag: local

replicas:
  - name: user-service
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: user-service-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "dev"
