apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SPRING_PROFILES_ACTIVE: "default"
  AUTH_SERVICE_PORT: "8080"
  # Redis
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8081"
  # OAuth2 설정 - K8s Ingress용 (localhost:80)
  OAUTH2_REDIRECT_URL_ENV: "http://localhost/oauth/callback"
  OAUTH2_CLIENT_REDIRECT_URI: "http://localhost/login/oauth2/code/google"
