# Auth Service Secret
# cp secret.yaml.example secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  JWT_SECRET: "local-dev-jwt-secret-min-32-characters-here"
  GOOGLE_CLIENT_ID: "input-id"
  GOOGLE_CLIENT_SECRET: "input-secret"
