apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "user_service"
  SPRING_DATASOURCE_PASSWORD: "user_service_password"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-min-32-chars"
  GOOGLE_CLIENT_ID: "your-google-client-id.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
