apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

images:
  - name: wealist/video-service
    newName: video-service
    newTag: local

replicas:
  - name: video-service
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: video-service-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: "dev"
