apiVersion: v1
kind: ConfigMap
metadata:
  name: video-service-config
data:
  ENV: "dev"
  PORT: "8003"
  SERVER_BASE_PATH: "/api/video"
  LOG_LEVEL: "debug"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://auth-service:8090"
  USER_SERVICE_URL: "http://user-service:8080/api/users"
  LIVEKIT_HOST: "http://livekit:7880"
  LIVEKIT_WS_URL: "ws://livekit:7880"
