apiVersion: v1
kind: Secret
metadata:
  name: video-service-secret
type: Opaque
stringData:
  DB_USER: "video_service"
  DB_PASSWORD: "video_service_password"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-min-32-chars"
  REDIS_PASSWORD: "redis_password"
  LIVEKIT_API_KEY: "devkey"
  LIVEKIT_API_SECRET: "secret"
