apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-local

resources:
  - ../../base

images:
  - name: frontend
    newName: localhost:5001/frontend
    newTag: v1

replicas:
  - name: frontend
    count: 1
