apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-app

resources:
  - ../../base

images:
  - name: chat-service
    newName: chat-service
    newTag: local

replicas:
  - name: chat-service
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: chat-service-config
    patch: |-
      - op: replace
        path: /data/GIN_MODE
        value: "debug"
